version: "3.0"
services:
  client:
    image: headless_player_component
    entrypoint: ["tail", "-f", "/dev/null"]
    container_name: client
    volumes:
      - ./Results:/Results
  server:
    build: ./server
    container_name: server
    cap_add:
    - NET_ADMIN

